batch_size: 16
height: 40
learning_rate: 0.001
max_text_length: 5
model_path: Models/captcha_to_text\202502201800
train_epochs: 300
train_workers: 20
vocab: gdp29L4qH1KjXtnmZNcyI8JR6SDxlkazWCAPOsiYv5Vwe37hBGrfUEubQMTF
width: 150
